[workspace]

members = [
    "adv-2023-common",
    "adv-2023-day1",
    "adv-2023-day2",
    "adv-2023-day3",
    "adv-2023-day4",
    "adv-2023-day5",
]

resolver = "2"

[workspace.package]
edition = "2021"
